apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-repo
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/baziwane/package-demo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image-registry
spec:
  type: image
  params:
    - name: url
      value: docker.pkg.github.com/baziwane/package-demo/packagedemoapp:latest
